# Function 4: Part 2 analysis notebook

This notebook keeps the original data-loading cells, appends the latest query point/output from the end of your uploaded notebook, and then runs one focused analysis for Part 2.

Assumption: lower output is better, so the optimisation target is minimisation.


In [1]:
import numpy as np

input_data = np.load('../../data/initial_data/function_4/initial_inputs.npy')
print("Before:", input_data.shape)
new_point = np.array([
    [0.273303, 0.432684, 0.384952, 0.414213],
    [0.360858, 0.334696, 0.389935, 0.443739],
    [0.5, 0.5, 0.5, 0.5]
    ])
input_data = np.vstack([input_data, new_point])
print("After:", input_data.shape)
print(input_data)


Before: (30, 4)
After: (33, 4)
[[0.89698105 0.72562797 0.17540431 0.70169437]
 [0.8893564  0.49958786 0.53926886 0.50878344]
 [0.25094624 0.03369313 0.14538002 0.49493242]
 [0.34696206 0.0062504  0.76056361 0.61302356]
 [0.12487118 0.12977019 0.38440048 0.2870761 ]
 [0.80130271 0.50023109 0.70664456 0.19510284]
 [0.24770826 0.06044543 0.04218635 0.44132425]
 [0.74670224 0.7570915  0.36935306 0.20656628]
 [0.40066503 0.07257425 0.88676825 0.24384229]
 [0.6260706  0.58675126 0.43880578 0.77885769]
 [0.95713529 0.59764438 0.76611385 0.77620991]
 [0.73281243 0.14524998 0.47681272 0.13336573]
 [0.65511548 0.07239183 0.68715175 0.08151656]
 [0.21973443 0.83203134 0.48286416 0.08256923]
 [0.48859419 0.2119651  0.93917791 0.37619173]
 [0.16713049 0.87655456 0.21723954 0.95980098]
 [0.21691119 0.16608583 0.24137226 0.77006248]
 [0.38748784 0.80453226 0.75179548 0.72382744]
 [0.98562189 0.66693268 0.15678328 0.8565348 ]
 [0.03782483 0.66485335 0.16198218 0.25392378]
 [0.68348638 0.9027701  0.335

In [ ]:
output_data = np.load('../../data/initial_data/function_4/initial_outputs.npy')
print("Before:", output_data.shape)
new_output = np.array([
    -1.1816448371847552,
    0.029304207874674137,
    -0.015979341188442648
    ])
output_data = np.append(output_data, new_output)
print("After:", output_data.shape)
print(output_data)


Before: (30,)
After: (32,)
[-2.21082878e+01 -1.46013966e+01 -1.16999325e+01 -1.60537651e+01
 -1.00696334e+01 -1.54870825e+01 -1.26816850e+01 -1.60263998e+01
 -1.70492346e+01 -1.27417660e+01 -2.73163964e+01 -1.35276489e+01
 -1.66791152e+01 -1.65071586e+01 -1.78179993e+01 -2.65618208e+01
 -1.27583242e+01 -1.94415576e+01 -2.89032737e+01 -1.37027469e+01
 -2.94270914e+01 -1.15657420e+01 -2.68577864e+01 -7.96677535e+00
 -6.70208925e+00 -3.26256602e+01 -1.99894979e+01 -4.02554228e+00
 -1.31227823e+01 -2.31394284e+01 -1.18164484e+00  2.93042079e-02]


In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Latest query/output extracted from the uploaded notebook.
# Edit these if you later receive a different portal output.
latest_query = np.array([[0.5, 0.5, 0.5, 0.5]])
actual_output = -3.985750969810286

# Append the latest query/output only if it is not already present.
if actual_output is not None:
    already_present = np.any(np.all(np.isclose(input_data, latest_query, atol=1e-12), axis=1))
    if not already_present:
        input_data = np.vstack([input_data, latest_query])
        output_data = np.append(output_data, actual_output)

function_id = 4
d = input_data.shape[1]
print(f"Function {function_id}, dimension d={d}")
print("Data shape:", input_data.shape, output_data.shape)
print("Current best observed y:", output_data.min())
print("Current best x:", input_data[np.argmin(output_data)])


Function 4, dimension d=4
Data shape: (33, 4) (33,)
Current best observed y: -32.625660215962455
Current best x: [0.94838936 0.89451301 0.85163782 0.55219629]


In [4]:
# Basic table used in all interpretations
summary = pd.DataFrame(input_data, columns=[f"x{i+1}" for i in range(d)])
summary["y"] = output_data
summary["log_abs_y"] = np.log(np.abs(output_data) + 1e-300)
summary["rank_min"] = summary["y"].rank(method="first", ascending=True).astype(int)
summary = summary.sort_values("y")
display(summary)


,x1,x2,x3,x4,y,log_abs_y,rank_min
25,0.948389,0.894513,0.851638,0.552196,-32.625660,3.485099,1
20,0.683486,0.902770,0.335420,0.999483,-29.427091,3.381916,2
18,0.985622,0.666933,0.156783,0.856535,-28.903274,3.363955,3
10,0.957135,0.597644,0.766114,0.776210,-27.316396,3.307487,4
22,0.859657,0.919592,0.206139,0.097797,-26.857786,3.290556,5
15,0.167130,0.876555,0.217240,0.959801,-26.561821,3.279475,6
29,0.854811,0.493965,0.735310,0.808092,-23.139428,3.141538,7
0,0.896981,0.725628,0.175404,0.701694,-22.108288,3.095953,8
26,0.664955,0.046566,0.116777,0.793718,-19.989498,2.995207,9
17,0.387488,0.804532,0.751795,0.723827,-19.441558,2.967413,10


## Neural-network surrogate + input gradients

In [5]:
import torch
import torch.nn as nn
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, r2_score

# Fit a small neural network to y. If the output scale is extreme, use log|y| instead.
# This cell automatically chooses log|y| if the ratio of magnitudes is very large or if values are near zero.
X = input_data.astype(np.float32)
y_raw = output_data.astype(np.float32)
use_log_abs = (np.nanmax(np.abs(y_raw)) / max(np.nanmin(np.abs(y_raw) + 1e-300), 1e-300) > 1e4)

y_target = np.log(np.abs(y_raw) + 1e-300).astype(np.float32) if use_log_abs else y_raw.copy()
target_name = "log_abs_y" if use_log_abs else "y"

x_scaler = StandardScaler()
y_scaler = StandardScaler()
X_scaled = x_scaler.fit_transform(X).astype(np.float32)
y_scaled = y_scaler.fit_transform(y_target.reshape(-1, 1)).astype(np.float32).ravel()

X_t = torch.tensor(X_scaled, dtype=torch.float32)
y_t = torch.tensor(y_scaled.reshape(-1, 1), dtype=torch.float32)

class SurrogateNN(nn.Module):
    def __init__(self, d):
        super().__init__()
        width = max(16, 4*d)
        self.net = nn.Sequential(
            nn.Linear(d, width), nn.Tanh(),
            nn.Linear(width, width), nn.Tanh(),
            nn.Linear(width, 1)
        )
    def forward(self, x):
        return self.net(x)

torch.manual_seed(0)
model = SurrogateNN(d)
opt = torch.optim.AdamW(model.parameters(), lr=0.01, weight_decay=1e-3)
loss_fn = nn.MSELoss()

for epoch in range(3000):
    opt.zero_grad()
    pred = model(X_t)
    loss = loss_fn(pred, y_t)
    loss.backward()
    opt.step()

with torch.no_grad():
    pred_scaled = model(X_t).numpy().ravel()
    pred_target = y_scaler.inverse_transform(pred_scaled.reshape(-1, 1)).ravel()

print("Target modelled:", target_name)
print(f"In-sample MSE in target space: {mean_squared_error(y_target, pred_target):.6g}")
print(f"In-sample R² in target space: {r2_score(y_target, pred_target):.4f}")


Target modelled: y
In-sample MSE in target space: 9.391e-06
In-sample R² in target space: 1.0000


In [6]:
# Compute gradients of the network prediction with respect to original input variables.
X_grad = torch.tensor(X_scaled, dtype=torch.float32, requires_grad=True)
pred = model(X_grad)

# Sum is used so autograd gives one gradient per input point.
pred.sum().backward()
grad_scaled = X_grad.grad.detach().numpy()

# Convert from scaled-input / scaled-output gradient to original input scale.
grad_target = grad_scaled * (y_scaler.scale_[0] / x_scaler.scale_)
grad_norm = np.linalg.norm(grad_target, axis=1)

grad_df = pd.DataFrame(input_data, columns=[f"x{i+1}" for i in range(d)])
grad_df["y"] = output_data
grad_df[target_name] = y_target
for j in range(d):
    grad_df[f"grad_x{j+1}"] = grad_target[:, j]
grad_df["grad_norm"] = grad_norm
grad_df["dominant_variable"] = [f"x{np.argmax(np.abs(row))+1}" for row in grad_target]

display(grad_df.sort_values("grad_norm", ascending=False))

avg_abs_grad = np.mean(np.abs(grad_target), axis=0)
print("Average absolute gradient:")
for j, val in enumerate(avg_abs_grad):
    print(f"x{j+1}: {val:.6g}")
print("Most influential variable on average:", f"x{np.argmax(avg_abs_grad)+1}")


,x1,x2,x3,x4,y,grad_x1,grad_x2,grad_x3,grad_x4,grad_norm,dominant_variable
16,0.216911,0.166086,0.241372,0.770062,-12.758325,4.390428,-0.127286,67.144698,-12.214779,68.387889,x3
17,0.387488,0.804532,0.751795,0.723827,-19.441557,-24.396327,-59.354671,2.790434,-6.160984,64.528304,x2
26,0.664955,0.046566,0.116777,0.793718,-19.989498,-2.631810,-14.436181,54.096450,-19.860223,59.465823,x3
19,0.037825,0.664853,0.161982,0.253924,-13.702747,2.619493,-24.879673,52.276598,4.385017,58.119970,x3
9,0.626071,0.586751,0.438806,0.778858,-12.741766,-22.552843,-39.953982,24.759383,-25.084267,57.854982,x2
7,0.746702,0.757092,0.369353,0.206566,-16.026400,-18.299709,-48.329593,-19.596536,12.431567,56.649774,x2
4,0.124871,0.129770,0.384400,0.287076,-10.069633,14.671218,49.086930,-22.942784,-1.207264,56.148020,x2
29,0.854811,0.493965,0.735310,0.808092,-23.139429,-29.441163,-7.799967,-42.516950,-18.047183,55.326426,x3
11,0.732812,0.145250,0.476813,0.133366,-13.527649,-19.212204,33.713983,-23.255637,27.529481,52.956948,x2
1,0.889356,0.499588,0.539269,0.508783,-14.601397,-36.246084,-22.929386,-27.386515,-6.704285,51.327420,x1


Average absolute gradient:
x1: 11.8035
x2: 21.9035
x3: 20.8723
x4: 15.4918
Most influential variable on average: x2


In [ ]:
# Use the neural network to propose a point by searching random candidates.
# For minimisation, choose low predicted target. If target is log_abs_y, this finds small magnitude, not necessarily negative y.
rng = np.random.default_rng(2)
candidates = rng.random((30000 if d <= 4 else 60000, d)).astype(np.float32)
cand_scaled = x_scaler.transform(candidates).astype(np.float32)
with torch.no_grad():
    pred_scaled = model(torch.tensor(cand_scaled)).numpy().ravel()
    pred_target = y_scaler.inverse_transform(pred_scaled.reshape(-1, 1)).ravel()

nn_results = pd.DataFrame(candidates, columns=[f"x{i+1}" for i in range(d)])
nn_results[f"pred_{target_name}"] = pred_target
nn_results = nn_results.sort_values(f"pred_{target_name}", ascending=True)
display(nn_results.head(10))

best_nn = nn_results.iloc[0][[f"x{i+1}" for i in range(d)]].to_numpy(float)
print("NN suggested point:", np.round(best_nn, 6))
print("Portal format:", ", ".join(f"x{i+1}={v:.6f}" for i, v in enumerate(best_nn)))
