# Function 4: Part 2 analysis notebook

This notebook keeps the original data-loading cells, appends the latest query point/output from the end of your uploaded notebook, and then runs one focused analysis for Part 2.

Assumption: lower output is better, so the optimisation target is minimisation.


In [2]:
import numpy as np

input_data = np.load('../../data/initial_data/function_4/initial_inputs.npy')
print("Before:", input_data.shape)
new_point = np.array([
    [0.273303, 0.432684, 0.384952, 0.414213],
    [0.360858, 0.334696, 0.389935, 0.443739],
    [0.5, 0.5, 0.5, 0.5]
    ])
input_data = np.vstack([input_data, new_point])
print("After:", input_data.shape)
print(input_data)


Before: (30, 4)
After: (33, 4)
[[0.89698105 0.72562797 0.17540431 0.70169437]
 [0.8893564  0.49958786 0.53926886 0.50878344]
 [0.25094624 0.03369313 0.14538002 0.49493242]
 [0.34696206 0.0062504  0.76056361 0.61302356]
 [0.12487118 0.12977019 0.38440048 0.2870761 ]
 [0.80130271 0.50023109 0.70664456 0.19510284]
 [0.24770826 0.06044543 0.04218635 0.44132425]
 [0.74670224 0.7570915  0.36935306 0.20656628]
 [0.40066503 0.07257425 0.88676825 0.24384229]
 [0.6260706  0.58675126 0.43880578 0.77885769]
 [0.95713529 0.59764438 0.76611385 0.77620991]
 [0.73281243 0.14524998 0.47681272 0.13336573]
 [0.65511548 0.07239183 0.68715175 0.08151656]
 [0.21973443 0.83203134 0.48286416 0.08256923]
 [0.48859419 0.2119651  0.93917791 0.37619173]
 [0.16713049 0.87655456 0.21723954 0.95980098]
 [0.21691119 0.16608583 0.24137226 0.77006248]
 [0.38748784 0.80453226 0.75179548 0.72382744]
 [0.98562189 0.66693268 0.15678328 0.8565348 ]
 [0.03782483 0.66485335 0.16198218 0.25392378]
 [0.68348638 0.9027701  0.335

In [4]:
output_data = np.load('../../data/initial_data/function_4/initial_outputs.npy')
print("Before:", output_data.shape)
new_output = np.array([
    -1.1816448371847552,
    0.029304207874674137,
    -0.015979341188442648
    ])
output_data = np.append(output_data, new_output)
print("After:", output_data.shape)
print(output_data)


Before: (30,)
After: (33,)
[-2.21082878e+01 -1.46013966e+01 -1.16999325e+01 -1.60537651e+01
 -1.00696334e+01 -1.54870825e+01 -1.26816850e+01 -1.60263998e+01
 -1.70492346e+01 -1.27417660e+01 -2.73163964e+01 -1.35276489e+01
 -1.66791152e+01 -1.65071586e+01 -1.78179993e+01 -2.65618208e+01
 -1.27583242e+01 -1.94415576e+01 -2.89032737e+01 -1.37027469e+01
 -2.94270914e+01 -1.15657420e+01 -2.68577864e+01 -7.96677535e+00
 -6.70208925e+00 -3.26256602e+01 -1.99894979e+01 -4.02554228e+00
 -1.31227823e+01 -2.31394284e+01 -1.18164484e+00  2.93042079e-02
 -1.59793412e-02]


In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Latest query/output extracted from the uploaded notebook.
# Edit these if you later receive a different portal output.
latest_query = np.array([[0.5, 0.5, 0.5, 0.5]])
actual_output = -3.985750969810286

# Append the latest query/output only if it is not already present.
if actual_output is not None:
    already_present = np.any(np.all(np.isclose(input_data, latest_query, atol=1e-12), axis=1))
    if not already_present:
        input_data = np.vstack([input_data, latest_query])
        output_data = np.append(output_data, actual_output)

function_id = 4
d = input_data.shape[1]
print(f"Function {function_id}, dimension d={d}")
print("Data shape:", input_data.shape, output_data.shape)
print("Current best observed y:", output_data.min())
print("Current best x:", input_data[np.argmin(output_data)])


Function 4, dimension d=4
Data shape: (33, 4) (33,)
Current best observed y: -32.625660215962455
Current best x: [0.94838936 0.89451301 0.85163782 0.55219629]


In [4]:
# Basic table used in all interpretations
summary = pd.DataFrame(input_data, columns=[f"x{i+1}" for i in range(d)])
summary["y"] = output_data
summary["log_abs_y"] = np.log(np.abs(output_data) + 1e-300)
summary["rank_min"] = summary["y"].rank(method="first", ascending=True).astype(int)
summary = summary.sort_values("y")
display(summary)


,x1,x2,x3,x4,y,log_abs_y,rank_min
25,0.948389,0.894513,0.851638,0.552196,-32.625660,3.485099,1
20,0.683486,0.902770,0.335420,0.999483,-29.427091,3.381916,2
18,0.985622,0.666933,0.156783,0.856535,-28.903274,3.363955,3
10,0.957135,0.597644,0.766114,0.776210,-27.316396,3.307487,4
22,0.859657,0.919592,0.206139,0.097797,-26.857786,3.290556,5
15,0.167130,0.876555,0.217240,0.959801,-26.561821,3.279475,6
29,0.854811,0.493965,0.735310,0.808092,-23.139428,3.141538,7
0,0.896981,0.725628,0.175404,0.701694,-22.108288,3.095953,8
26,0.664955,0.046566,0.116777,0.793718,-19.989498,2.995207,9
17,0.387488,0.804532,0.751795,0.723827,-19.441558,2.967413,10


## Gaussian process surrogate + expected improvement for minimisation

In [5]:
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import ConstantKernel, Matern, WhiteKernel
from sklearn.preprocessing import StandardScaler
from scipy.stats import norm

# Standardise inputs and outputs for numerical stability.
X = input_data.copy()
y = output_data.copy()

x_scaler = StandardScaler()
y_scaler = StandardScaler()
X_scaled = x_scaler.fit_transform(X)
y_scaled = y_scaler.fit_transform(y.reshape(-1, 1)).ravel()

kernel = ConstantKernel(1.0, (1e-3, 1e3)) * Matern(length_scale=np.ones(d), length_scale_bounds=(1e-2, 1e2), nu=2.5) + WhiteKernel(noise_level=1e-6, noise_level_bounds=(1e-10, 1e-1))

gp = GaussianProcessRegressor(kernel=kernel, normalize_y=False, n_restarts_optimizer=20, random_state=0)
gp.fit(X_scaled, y_scaled)

print("Fitted kernel:", gp.kernel_)
print("Best observed y:", y.min())
print("Best observed x:", X[np.argmin(y)])


Fitted kernel: 4.18**2 * Matern(length_scale=[6.51, 5.98, 7.67, 6.52], nu=2.5) + WhiteKernel(noise_level=0.00118)
Best observed y: -32.625660215962455
Best observed x: [0.94838936 0.89451301 0.85163782 0.55219629]


In [6]:
def expected_improvement_min(X_candidates, gp, y_best_scaled, xi=0.01):
    """Expected improvement for minimisation in scaled y-space."""
    mu, sigma = gp.predict(X_candidates, return_std=True)
    sigma = np.maximum(sigma, 1e-12)
    improvement = y_best_scaled - mu - xi
    Z = improvement / sigma
    ei = improvement * norm.cdf(Z) + sigma * norm.pdf(Z)
    return ei

# Random candidate search in [0, 1]^d. Increase n_candidates for a more exhaustive search.
rng = np.random.default_rng(0)
n_candidates = 20000 if d <= 4 else 50000
candidates = rng.random((n_candidates, d))
candidates_scaled = x_scaler.transform(candidates)

y_best_scaled = y_scaled.min()
ei = expected_improvement_min(candidates_scaled, gp, y_best_scaled, xi=0.01)
mu_scaled, std_scaled = gp.predict(candidates_scaled, return_std=True)
mu = y_scaler.inverse_transform(mu_scaled.reshape(-1, 1)).ravel()
std = std_scaled * y_scaler.scale_[0]

results = pd.DataFrame(candidates, columns=[f"x{i+1}" for i in range(d)])
results["pred_mean"] = mu
results["pred_std"] = std
results["expected_improvement"] = ei
results = results.sort_values("expected_improvement", ascending=False)

display(results.head(10))

best_next = results.iloc[0][[f"x{i+1}" for i in range(d)]].to_numpy(dtype=float)
print("Suggested next query:", np.round(best_next, 6))
print("Portal format:", ", ".join(f"x{i+1}={v:.6f}" for i, v in enumerate(best_next)))


,x1,x2,x3,x4,pred_mean,pred_std,expected_improvement
17575,0.987402,0.981638,0.984172,0.870955,-41.914059,3.480208,1.143043
8738,0.932161,0.928077,0.981872,0.983081,-41.129407,3.979783,1.048189
5877,0.955210,0.944733,0.893554,0.978771,-40.486628,3.481535,0.967294
14822,0.932863,0.926441,0.980841,0.881015,-39.591400,3.109423,0.856113
10347,0.986930,0.959436,0.750412,0.946900,-39.078433,2.838073,0.792166
15678,0.944736,0.919815,0.927535,0.894610,-38.924420,2.821331,0.773236
14694,0.956460,0.952135,0.084099,0.999960,-38.610178,2.580978,0.733770
11273,0.929936,0.923870,0.920230,0.890660,-38.465801,2.749655,0.716879
17984,0.973923,0.944265,0.968833,0.670905,-38.237638,1.695493,0.686360
17122,0.996916,0.905636,0.096402,0.979354,-38.054762,2.257908,0.664475


Suggested next query: [0.987402 0.981638 0.984172 0.870955]
Portal format: x1=0.987402, x2=0.981638, x3=0.984172, x4=0.870955


In [7]:
# Optional 2D visualisation only when d=2
if d == 2:
    grid_res = 150
    xx, yy = np.meshgrid(np.linspace(0, 1, grid_res), np.linspace(0, 1, grid_res))
    grid = np.c_[xx.ravel(), yy.ravel()]
    grid_scaled = x_scaler.transform(grid)
    mu_grid_scaled, std_grid_scaled = gp.predict(grid_scaled, return_std=True)
    mu_grid = y_scaler.inverse_transform(mu_grid_scaled.reshape(-1, 1)).reshape(grid_res, grid_res)
    ei_grid = expected_improvement_min(grid_scaled, gp, y_best_scaled).reshape(grid_res, grid_res)

    plt.figure(figsize=(7, 6))
    cf = plt.contourf(xx, yy, mu_grid, levels=40)
    plt.colorbar(cf, label="GP predicted mean")
    plt.scatter(input_data[:, 0], input_data[:, 1], c=output_data, edgecolors="black", s=80)
    plt.scatter(best_next[0], best_next[1], marker="*", s=250, edgecolors="black", label="suggested next")
    plt.xlabel("x1"); plt.ylabel("x2"); plt.title("GP predicted mean")
    plt.legend(); plt.show()

    plt.figure(figsize=(7, 6))
    cf = plt.contourf(xx, yy, ei_grid, levels=40)
    plt.colorbar(cf, label="Expected improvement")
    plt.scatter(input_data[:, 0], input_data[:, 1], c="white", edgecolors="black", s=80)
    plt.scatter(best_next[0], best_next[1], marker="*", s=250, edgecolors="black", label="suggested next")
    plt.xlabel("x1"); plt.ylabel("x2"); plt.title("Expected improvement for minimisation")
    plt.legend(); plt.show()
