# Function 4: Part 2 analysis notebook

This notebook keeps the original data-loading cells, appends the latest query point/output from the end of your uploaded notebook, and then runs one focused analysis for Part 2.

Assumption: lower output is better, so the optimisation target is minimisation.


In [1]:
import numpy as np

input_data = np.load('../../data/initial_data/function_4/initial_inputs.npy')
print("Before:", input_data.shape)
new_point = np.array([
    [0.273303, 0.432684, 0.384952, 0.414213],
    [0.360858, 0.334696, 0.389935, 0.443739],
    [0.5, 0.5, 0.5, 0.5]
    ])
input_data = np.vstack([input_data, new_point])
print("After:", input_data.shape)
print(input_data)


Before: (30, 4)
After: (33, 4)
[[0.89698105 0.72562797 0.17540431 0.70169437]
 [0.8893564  0.49958786 0.53926886 0.50878344]
 [0.25094624 0.03369313 0.14538002 0.49493242]
 [0.34696206 0.0062504  0.76056361 0.61302356]
 [0.12487118 0.12977019 0.38440048 0.2870761 ]
 [0.80130271 0.50023109 0.70664456 0.19510284]
 [0.24770826 0.06044543 0.04218635 0.44132425]
 [0.74670224 0.7570915  0.36935306 0.20656628]
 [0.40066503 0.07257425 0.88676825 0.24384229]
 [0.6260706  0.58675126 0.43880578 0.77885769]
 [0.95713529 0.59764438 0.76611385 0.77620991]
 [0.73281243 0.14524998 0.47681272 0.13336573]
 [0.65511548 0.07239183 0.68715175 0.08151656]
 [0.21973443 0.83203134 0.48286416 0.08256923]
 [0.48859419 0.2119651  0.93917791 0.37619173]
 [0.16713049 0.87655456 0.21723954 0.95980098]
 [0.21691119 0.16608583 0.24137226 0.77006248]
 [0.38748784 0.80453226 0.75179548 0.72382744]
 [0.98562189 0.66693268 0.15678328 0.8565348 ]
 [0.03782483 0.66485335 0.16198218 0.25392378]
 [0.68348638 0.9027701  0.335

In [2]:
output_data = np.load('../../data/initial_data/function_4/initial_outputs.npy')
print("Before:", output_data.shape)
new_output = np.array([
    -1.1816448371847552,
    0.029304207874674137,
    -0.015979341188442648
    ])
output_data = np.append(output_data, new_output)
print("After:", output_data.shape)
print(output_data)


Before: (30,)
After: (33,)
[-2.21082878e+01 -1.46013966e+01 -1.16999325e+01 -1.60537651e+01
 -1.00696334e+01 -1.54870825e+01 -1.26816850e+01 -1.60263998e+01
 -1.70492346e+01 -1.27417660e+01 -2.73163964e+01 -1.35276489e+01
 -1.66791152e+01 -1.65071586e+01 -1.78179993e+01 -2.65618208e+01
 -1.27583242e+01 -1.94415576e+01 -2.89032737e+01 -1.37027469e+01
 -2.94270914e+01 -1.15657420e+01 -2.68577864e+01 -7.96677535e+00
 -6.70208925e+00 -3.26256602e+01 -1.99894979e+01 -4.02554228e+00
 -1.31227823e+01 -2.31394284e+01 -1.18164484e+00  2.93042079e-02
 -1.59793412e-02]


In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Latest query/output extracted from the uploaded notebook.
# Edit these if you later receive a different portal output.
latest_query = np.array([[0.5, 0.5, 0.5, 0.5]])
actual_output = -3.985750969810286

# Append the latest query/output only if it is not already present.
if actual_output is not None:
    already_present = np.any(np.all(np.isclose(input_data, latest_query, atol=1e-12), axis=1))
    if not already_present:
        input_data = np.vstack([input_data, latest_query])
        output_data = np.append(output_data, actual_output)

function_id = 4
d = input_data.shape[1]
print(f"Function {function_id}, dimension d={d}")
print("Data shape:", input_data.shape, output_data.shape)
print("Current best observed y:", output_data.min())
print("Current best x:", input_data[np.argmin(output_data)])


Function 4, dimension d=4
Data shape: (33, 4) (33,)
Current best observed y: -32.625660215962455
Current best x: [0.94838936 0.89451301 0.85163782 0.55219629]


In [4]:
# Basic table used in all interpretations
summary = pd.DataFrame(input_data, columns=[f"x{i+1}" for i in range(d)])
summary["y"] = output_data
summary["log_abs_y"] = np.log(np.abs(output_data) + 1e-300)
summary["rank_min"] = summary["y"].rank(method="first", ascending=True).astype(int)
summary = summary.sort_values("y")
display(summary)


,x1,x2,x3,x4,y,log_abs_y,rank_min
25,0.948389,0.894513,0.851638,0.552196,-32.625660,3.485099,1
20,0.683486,0.902770,0.335420,0.999483,-29.427091,3.381916,2
18,0.985622,0.666933,0.156783,0.856535,-28.903274,3.363955,3
10,0.957135,0.597644,0.766114,0.776210,-27.316396,3.307487,4
22,0.859657,0.919592,0.206139,0.097797,-26.857786,3.290556,5
15,0.167130,0.876555,0.217240,0.959801,-26.561821,3.279475,6
29,0.854811,0.493965,0.735310,0.808092,-23.139428,3.141538,7
0,0.896981,0.725628,0.175404,0.701694,-22.108288,3.095953,8
26,0.664955,0.046566,0.116777,0.793718,-19.989498,2.995207,9
17,0.387488,0.804532,0.751795,0.723827,-19.441558,2.967413,10


## Classification framing: good vs bad outputs

In [5]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix

# Define "good" as the best quartile of observed outputs.
# For a very small dataset this gives enough positive labels to fit a classifier.
good_threshold = np.quantile(output_data, 0.25)
good_label = (output_data <= good_threshold).astype(int)

class_df = pd.DataFrame(input_data, columns=[f"x{i+1}" for i in range(d)])
class_df["y"] = output_data
class_df["good_label"] = good_label
class_df["distance_to_threshold"] = np.abs(output_data - good_threshold)
class_df["log_abs_y"] = np.log(np.abs(output_data) + 1e-300)
class_df = class_df.sort_values("distance_to_threshold")

print(f"Good/bad threshold: y <= {good_threshold:.6e}")
display(class_df)

print("Support-vector-like observed points:")
display(class_df.head(min(5, len(class_df))))


Good/bad threshold: y <= -1.998950e+01


,x1,x2,x3,x4,y,good_label,distance_to_threshold,log_abs_y
26,0.664955,0.046566,0.116777,0.793718,-19.989498,1,0.000000,2.995207
17,0.387488,0.804532,0.751795,0.723827,-19.441558,0,0.547940,2.967413
0,0.896981,0.725628,0.175404,0.701694,-22.108288,1,2.118790,3.095953
14,0.488594,0.211965,0.939178,0.376192,-17.817999,0,2.171499,2.880209
8,0.400665,0.072574,0.886768,0.243842,-17.049235,0,2.940263,2.836105
29,0.854811,0.493965,0.735310,0.808092,-23.139428,1,3.149930,3.141538
12,0.655115,0.072392,0.687152,0.081517,-16.679115,0,3.310383,2.814157
13,0.219734,0.832031,0.482864,0.082569,-16.507159,0,3.482339,2.803794
3,0.346962,0.006250,0.760564,0.613024,-16.053765,0,3.935733,2.775943
7,0.746702,0.757092,0.369353,0.206566,-16.026400,0,3.963098,2.774237


Support-vector-like observed points:


,x1,x2,x3,x4,y,good_label,distance_to_threshold,log_abs_y
26,0.664955,0.046566,0.116777,0.793718,-19.989498,1,0.000000,2.995207
17,0.387488,0.804532,0.751795,0.723827,-19.441558,0,0.547940,2.967413
0,0.896981,0.725628,0.175404,0.701694,-22.108288,1,2.118790,3.095953
14,0.488594,0.211965,0.939178,0.376192,-17.817999,0,2.171499,2.880209
8,0.400665,0.072574,0.886768,0.243842,-17.049235,0,2.940263,2.836105


In [6]:
X = input_data.copy()
y_cls = good_label
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

if len(np.unique(y_cls)) < 2:
    print("Only one class is present, so logistic/SVM classifiers cannot be fitted yet.")
else:
    log_reg = LogisticRegression(class_weight="balanced", random_state=0)
    svm_linear = SVC(kernel="linear", class_weight="balanced", probability=True, random_state=0)
    svm_rbf = SVC(kernel="rbf", C=10.0, gamma="scale", class_weight="balanced", probability=True, random_state=0)

    models = {"logistic": log_reg, "linear_svm": svm_linear, "rbf_svm": svm_rbf}
    for name, model in models.items():
        model.fit(X_scaled, y_cls)
        pred = model.predict(X_scaled)
        print("\n", name)
        print("Confusion matrix:\n", confusion_matrix(y_cls, pred))
        print(classification_report(y_cls, pred, zero_division=0))



 logistic
Confusion matrix:
 [[22  2]
 [ 0  9]]
              precision    recall  f1-score   support

           0       1.00      0.92      0.96        24
           1       0.82      1.00      0.90         9

    accuracy                           0.94        33
   macro avg       0.91      0.96      0.93        33
weighted avg       0.95      0.94      0.94        33


 linear_svm
Confusion matrix:
 [[21  3]
 [ 0  9]]
              precision    recall  f1-score   support

           0       1.00      0.88      0.93        24
           1       0.75      1.00      0.86         9

    accuracy                           0.91        33
   macro avg       0.88      0.94      0.90        33
weighted avg       0.93      0.91      0.91        33


 rbf_svm
Confusion matrix:
 [[24  0]
 [ 0  9]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        24
           1       1.00      1.00      1.00         9

    accuracy                      

In [7]:
# Boundary / uncertainty search: where classifier is closest to p(good)=0.5.
if len(np.unique(y_cls)) >= 2:
    rng = np.random.default_rng(1)
    candidates = rng.random((30000 if d <= 4 else 60000, d))
    cand_scaled = scaler.transform(candidates)

    rows = []
    for name, model in models.items():
        prob_good = model.predict_proba(cand_scaled)[:, 1]
        uncertainty = np.abs(prob_good - 0.5)
        idx = np.argsort(uncertainty)[:10]
        tmp = pd.DataFrame(candidates[idx], columns=[f"x{i+1}" for i in range(d)])
        tmp["model"] = name
        tmp["p_good"] = prob_good[idx]
        tmp["boundary_score_abs_p_minus_0.5"] = uncertainty[idx]
        rows.append(tmp)

    boundary_points = pd.concat(rows, ignore_index=True)
    display(boundary_points.sort_values("boundary_score_abs_p_minus_0.5").head(20))

    candidate = boundary_points.sort_values("boundary_score_abs_p_minus_0.5").iloc[0][[f"x{i+1}" for i in range(d)]].to_numpy(float)
    print("Most boundary-like candidate:", np.round(candidate, 6))
    print("Portal format:", ", ".join(f"x{i+1}={v:.6f}" for i, v in enumerate(candidate)))


,x1,x2,x3,x4,model,p_good,boundary_score_abs_p_minus_0.5
14,0.986442,0.875116,0.666406,0.247418,linear_svm,0.5,0.0
27,0.146137,0.083328,0.942022,0.939690,rbf_svm,0.5,0.0
26,0.369089,0.150352,0.201072,0.913023,rbf_svm,0.5,0.0
25,0.547860,0.725642,0.920952,0.687545,rbf_svm,0.5,0.0
24,0.723101,0.866060,0.529894,0.746532,rbf_svm,0.5,0.0
23,0.834760,0.954973,0.522810,0.106073,rbf_svm,0.5,0.0
22,0.477374,0.049726,0.742885,0.912379,rbf_svm,0.5,0.0
21,0.747308,0.211237,0.966572,0.484651,rbf_svm,0.5,0.0
20,0.941496,0.042041,0.973122,0.132703,rbf_svm,0.5,0.0
19,0.958116,0.322089,0.710739,0.661171,linear_svm,0.5,0.0


Most boundary-like candidate: [0.986442 0.875116 0.666406 0.247418]
Portal format: x1=0.986442, x2=0.875116, x3=0.666406, x4=0.247418


In [8]:
# Optional 2D plot
if d == 2 and len(np.unique(y_cls)) >= 2:
    grid_res = 200
    xx, yy = np.meshgrid(np.linspace(0, 1, grid_res), np.linspace(0, 1, grid_res))
    grid = np.c_[xx.ravel(), yy.ravel()]
    grid_scaled = scaler.transform(grid)
    for name, model in models.items():
        prob = model.predict_proba(grid_scaled)[:, 1].reshape(grid_res, grid_res)
        plt.figure(figsize=(7, 6))
        cf = plt.contourf(xx, yy, prob, levels=40)
        plt.colorbar(cf, label="Predicted P(good)")
        plt.contour(xx, yy, prob, levels=[0.5], linewidths=2)
        plt.scatter(input_data[:, 0], input_data[:, 1], c=good_label, edgecolors="black", s=80)
        plt.xlabel("x1"); plt.ylabel("x2"); plt.title(f"Good/bad boundary: {name}")
        plt.show()
